newsUrl: https://orz.ai/api/v1/dailynews/?platform=
platformCode: baidu
feishuWebhook: https://open.feishu.cn/open-apis/bot/v2/hook/8836666e-b0d3-43bf-beb8-82b774958d48
newsCount: 5
pushMsg: true
rebootType: feishu

log:
  path: logs
  level: "INFO"

secretKey: "01234567890abcdefghijklmnopqrstuvwxyz"
